modLoader="kotlinforforge"
loaderVersion="[1,)"
license="LGPL-3.0"
[[mods]]
modId="testcore"
version="0.0.0"
displayName="Test Core"
description="Infrastructure for testing LibrarianLib"
[[dependencies.testcore]]
    modId="librarianlib"
    versionRange="(0.0.0,]"
    mandatory=true
    ordering="AFTER"
