modLoader="kotlinforforge"
loaderVersion="[1,)"
license="LGPL-3.0"
[[mods]]
modId="ll-lieutenant"
version="0.0.0"
displayName="ll-lieutenant-test"
description=""
[[dependencies.ll-lieutenant]]
    modId="ll-core"
    versionRange="(0.0.0,]"
    mandatory=true
    ordering="BEFORE"