modLoader="javafml"
loaderVersion="[26,)"
issueTrackerURL="https://github.com/LibrarianLib/LibrarianLib/issues"
[[mods]]
modId="librarianlib-testbase"
version="${file.jarVersion}"
displayName="LibrarianLib Test Base"
# A URL to query for updates for this mod. See the JSON update specification <here>
# updateJSONURL="http://myurl.me/" #optional
# A URL for the "homepage" for this mod, displayed in the mod UI
# displayURL="http://example.com/" #optional
logoFile="icon.png"
# credits="Thanks for this example mod goes to Java"
# authors="Love, Cheese and small house plants" #optional
description='''
A set of base classes for LibrarianLib module tests
'''
[[dependencies.librarianlib-testbase]]
    modId="librarianlib-core"
    mandatory=true
    versionRange="*"
[[dependencies.librarianlib-testbase]]
    modId="librarianlib-virtualresources"
    mandatory=true
    versionRange="*"
