modLoader="kotlinforforge"
loaderVersion="[1,)"
license="LGPL-3.0"
[[mods]]
modId="ll-facade"
version="0.0.0"
displayName="Liblib Facade"
description=""
[[dependencies.ll-facade]]
    modId="ll-core"
    versionRange="[0.0.0,]"
    mandatory=true
    ordering="BEFORE"