modLoader="kotlinforforge"
loaderVersion="[1,)"
license="LGPL-3.0"
[[mods]]
modId="ll-courier"
version="0.0.0"
displayName="Liblib Courier"
description=""
[[dependencies.ll-courier]]
    modId="ll-core"
    versionRange="[0.0.0,]"
    mandatory=true
    ordering="BEFORE"